# Generated by Django 4.2.5 on 2023-11-15 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ware_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerModel',
        ),
    ]
