# Generated by Django 4.2.5 on 2023-11-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ware_app', '0002_delete_customermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('cs_email', models.EmailField(max_length=254)),
                ('cs_address', models.CharField(max_length=200)),
                ('cs_gender', models.CharField(max_length=100)),
                ('cs_pan', models.CharField(max_length=100)),
                ('cs_phone', models.IntegerField()),
                ('cs_image', models.ImageField(null=True, upload_to='image/')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
