# Generated by Django 4.2.5 on 2023-11-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ware_app', '0006_delivery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
