# Generated by Django 4.2.5 on 2023-11-15 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ware_app', '0007_delete_delivery_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dl_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('dl_email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_for', models.CharField(default='admin', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ware_app.customermodel')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ware_app.delivery')),
            ],
        ),
    ]
