# Generated by Django 4.2.5 on 2023-11-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ware_app', '0009_alter_notification_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('specifications', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initial_stock_quantity', models.PositiveIntegerField()),
            ],
        ),
    ]
