# Generated by Django 4.2.5 on 2023-11-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ware_app', '0012_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
