# Generated by Django 4.2.5 on 2023-11-17 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ware_app', '0022_shippingmethod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
