# Generated by Django 4.2.5 on 2023-11-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ware_app', '0024_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
