# Generated by Django 4.2.5 on 2023-11-17 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ware_app', '0025_order_tracking_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Dispatched', 'Dispatched'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ware_app.delivery')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ware_app.order')),
            ],
        ),
    ]
