# Generated by Django 4.2.5 on 2023-11-17 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ware_app', '0026_deliverystatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryStatus',
        ),
    ]
