# Generated by Django 4.2.5 on 2023-11-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ware_app', '0028_order_delivery_person_order_estimated_delivery_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location_dispatch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='location_transit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
