# Generated by Django 4.2.5 on 2023-11-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ware_app', '0029_order_location_dispatch_order_location_transit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_combined_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Dispatched', 'Dispatched'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='client_delivery_status',
            field=models.BooleanField(default=False),
        ),
    ]
